### ISSUE TITLE
Automatically create local sqlite db when sqlite is selected

### ISSUE THREAD

**Issue by illogikal** [formidablejs/installer#34]

**Comment by donaldp** [comment]
@illogikal do you think the local sqlite db file should be omitted from git?
Here's the current pr draft https://github.com/formidablejs/installer/pull/43/files

**Comment by illogikal** [comment]
Maybe this can also be something the user decides. If I am working on a personal project, then I would prefer to kee it in the repo, but if multiple people would use it maybe not...

**Comment by donaldp** [comment]
Feature implemented in [https://github.com/formidablejs/installer/pull/43/files](https://github.com/formidablejs/installer/pull/43/files)
