### ISSUE TITLE
Add Language question to the Formidable Installer

### ISSUE THREAD

**Issue by donaldp** [formidablejs/installer#78]
## Description
Add a new question to allow users to pick their preferred language.

### Question:
What Programming Language would you like to use?

### Options:
* Imba (default)
* TypeScript

## Notes
The Formidable installer already supports TypeScript through the `--ts` flag. The new flow needs to allow the user to pick between the listed options above.

#### Onboard
https://github.com/formidablejs/installer/blob/main/src/onboard/Type.ts

#### Command Flag
https://github.com/formidablejs/installer/blob/6da0e91783713e053900c59a9b4fcbff6ba3b4f4/src/commands/new.ts#L37

#### Flag defaults
https://github.com/formidablejs/installer/blob/6da0e91783713e053900c59a9b4fcbff6ba3b4f4/src/commands/new.ts#L112

#### Scaffold
https://github.com/formidablejs/installer/blob/main/src/utils/scaffold.ts

**Comment by Nirbhayparmar** [comment]
I don't have any experience in typescript or formidable js but I can dig deeper for some time and try to understand this, than i might be able to work on this.

**Comment by Nirbhayparmar** [comment]
Can you give me more insights about this project?

**Comment by donaldp** [comment]
@Nirbhayparmar of course, are you on discord?

**Comment by Nirbhayparmar** [comment]
yes my discord username is - Nirbhay Parmar(P)#3624

**Comment by donaldp** [comment]
Feature implemented
